"""Engineer guidance rendering.

When the decision node rules out automation, the deliverable is a
structured hand-off document a cloud engineer can execute directly.
Pure rendering — no LLM, no I/O.
"""

from __future__ import annotations

from src.chandra.digital_worker.schemas import (
    CloudRequest,
    ContextBundle,
    RequestClassification,
    ResolutionPlan,
    RiskAssessment,
    RootCause,
)


def render_guidance(
    request: CloudRequest,
    classification: RequestClassification,
    root_cause: RootCause,
    plan: ResolutionPlan,
    risk: RiskAssessment,
    context: ContextBundle,
) -> str:
    """Render the engineer hand-off document as Markdown."""
    lines: list[str] = [
        f"# Engineer Guidance — {request.title}",
        "",
        f"- **Request ID**: `{request.request_id}`",
        f"- **Source**: {request.source.value}"
        + (f" (`{request.external_id}`)" if request.external_id else ""),
        f"- **Category**: {classification.category.value}",
        f"- **Platform**: {classification.platform.value}",
        f"- **Priority**: {classification.priority.value}",
        f"- **Risk**: {risk.level.value} (score {risk.score}/100)"
        + (" — requires approval" if risk.requires_approval else ""),
        "",
        "## Root cause analysis",
        root_cause.summary or "_No root cause determined._",
    ]
    if root_cause.probable_causes:
        lines.append("")
        lines.append("Probable causes:")
        lines.extend(f"1. {cause}" for cause in root_cause.probable_causes)

    lines.extend(["", "## Recommended resolution steps", ""])
    if plan.steps:
        for step in plan.steps:
            lines.append(f"{step.order}. **{step.action}**")
            if step.detail:
                lines.append(f"   - {step.detail}")
            if step.command:
                lines.append(f"   - Command: `{step.command}`")
            if step.expected_outcome:
                lines.append(f"   - Expect: {step.expected_outcome}")
    else:
        lines.append("_No concrete steps could be derived; investigate manually._")

    if plan.rollback_steps:
        lines.extend(["", "## Rollback", ""])
        lines.extend(f"{step.order}. {step.action}" for step in plan.rollback_steps)

    if risk.factors:
        lines.extend(["", "## Risk factors", ""])
        lines.extend(f"- {factor}" for factor in risk.factors)

    if context.items:
        lines.extend(["", "## Evidence collected", ""])
        lines.extend(f"- [{item.kind}] {item.provider}: {item.summary}" for item in context.items)
    if context.errors:
        lines.extend(["", "## Context gaps", ""])
        lines.extend(f"- {error}" for error in context.errors)

    lines.append("")
    lines.append(f"_Plan generated by: {plan.generated_by}._")
    return "\n".join(lines)
