"""add_bedrock_cost_column

Revision ID: 4bf06f1cc514
Revises: 0001
Create Date: 2026-06-03 17:09:12.372150
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = '4bf06f1cc514'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('bedrock_cost_usd', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'bedrock_cost_usd')
    # ### end Alembic commands ###
