"""Add bedrock_cost_usd to runs

Revision ID: c6f417c05ab8
Revises: 0001
Create Date: 2026-06-03 16:36:52.066565
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c6f417c05ab8'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('runs', sa.Column('bedrock_cost_usd', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'bedrock_cost_usd')

    # ### end Alembic commands ###
